# Generated by Django 3.2.6 on 2021-08-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CONTACT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DIRECTORS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Image', models.FileField(upload_to='Team')),
                ('FB_Account', models.CharField(max_length=200)),
                ('Twitter_Account', models.CharField(max_length=200)),
                ('Instagram_Account', models.CharField(max_length=200)),
                ('LinkedIn_Account', models.CharField(max_length=200)),
            ],
        ),
    ]
