# Generated by Django 3.2.6 on 2021-09-06 08:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BLOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Date_Created', models.DateTimeField(default=datetime.datetime.now)),
                ('Image', models.ImageField(upload_to='Blogs')),
                ('ABOUT', models.CharField(blank=True, choices=[('WEB', 'WEB'), ('ADROID', 'ADROID'), ('DESKTOP', 'DESKTOP'), ('SYSTEMS', 'SYSTEMS')], max_length=200, null=True)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CONTACT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DIRECTORS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Image', models.FileField(upload_to='Team')),
                ('FB_Account', models.CharField(blank=True, max_length=200, null=True)),
                ('Twitter_Account', models.CharField(blank=True, max_length=200, null=True)),
                ('Instagram_Account', models.CharField(blank=True, max_length=200, null=True)),
                ('LinkedIn_Account', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PROJECT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Type', models.CharField(default='Web-App', max_length=200)),
                ('Link', models.CharField(blank=True, max_length=200, null=True)),
                ('Display_Image', models.FileField(upload_to='Projects')),
            ],
        ),
        migrations.CreateModel(
            name='PROFILE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=200)),
                ('LName', models.CharField(max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Image', models.ImageField(upload_to='Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
