# Generated by Django 3.2.6 on 2021-08-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directors',
            name='Description',
            field=models.TextField(),
        ),
    ]
