# Generated by Django 3.2.6 on 2021-08-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTK', '0002_alter_directors_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directors',
            name='FB_Account',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='directors',
            name='Instagram_Account',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='directors',
            name='LinkedIn_Account',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='directors',
            name='Twitter_Account',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
