# Generated by Django 3.2.6 on 2021-08-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTK', '0004_auto_20210814_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROJECT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Type', models.CharField(default='Web-App', max_length=200)),
                ('Link', models.CharField(blank=True, max_length=200, null=True)),
                ('Display_Image', models.FileField(upload_to='Projects')),
            ],
        ),
    ]
