# Generated by Django 3.2.6 on 2021-08-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTK', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
