# Generated by Django 3.2.6 on 2021-08-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTK', '0009_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='About',
            field=models.CharField(blank=True, choices=[('WEB', 'WEB'), ('ADROID', 'ADROID'), ('DESKTOP', 'DESKTOP'), ('SYSTEMS', 'SYSTEMS')], max_length=200, null=True),
        ),
    ]
