# Generated by Django 3.2.6 on 2021-08-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TTK', '0010_blog_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='About',
            new_name='ABOUT',
        ),
    ]
